### ISSUE TITLE
bash_profile vs bashrc

### ISSUE THREAD

**Issue by dlcarmean** [revans/bash-it#173]
Forgive me if this has been raised and decided, but the issue searchbox did not reveal such...

I'm wondering why this toolkit focuses on wedging into .bash_profile when .bashrc seems to be generally accepted as the starting point for interactive bash sessions?

I follow what I'd gathered to be a generally accepted practice of a trivial bash_profile which exists primarily to invoke .bashrc, whose only other entries are to configure items I'd use from cron or some remote execution tool.

(in fact I carry this a bit further, having a separate .bashrc.interactive or .bashrc.local for the truly local interactive stuff).

I'm busily hacking on my own local branch to refactor for the above, but want to step back and think about how I can give back.  

(background:  I spend hours logged in as the daemon user for a particular application for administration.  I'm hoping this toolkit can help me standardize those admin environments but my prime directive is "First, do no harm" to the app's auto-customized shell environment.   I'm leaning toward an installation that requires manual sourcing for that particular environment, but elsewhere, a cleaner merge into existing startup files.)

**Comment by edubxb** [comment]
I'm planning to modify the installer to detect the OS and choose the file to write the config:

Mac OS X  → .bash_profile
Other *nix → .bashrc

Any objections?

**Comment by RobLoach** [comment]
:+1:

**Comment by nwinkler** [comment]
Great idea! :+1:

**Comment by seefood** [comment]
Also Debian+derivs (Ubuntu, Mint) prefer .bash_profile, I think.

**Comment by edubxb** [comment]
I use Debian, at home and at work, Unstable and Testing, and in both cases, the scenario is the explained in my previous comment #173 (comment).

You can check it viewing the files:

    /etc/skel/.bashrc
    /etc/skel/.profile

the default config files copied to the home of new created users. If `.bash_profile` exists `.profile` is ignored.

The original idea comes from @tswicegood in this comment https://github.com/revans/bash-it/issues/173#issuecomment-13499754 :sweat_smile:
