### ISSUE TITLE
pass function in plugins/available/base.plugin.bash  vs pass (password-store)

### ISSUE THREAD

**Issue by scmorrison** [revans/bash-it#399]
Hi all, there is a popular password utility called pass (http://www.passwordstore.org/) that doesn't work with bash-it without modification or disabling the base.plugin.bash.

Would it be possible to rename the pass() function so that bash-it works with the base.plugin.bash enabled when the user is also using the pass utility?

For compatibility, there is another common command called pwgen that generates passwords. If you do decide to rename the pass() function, pwgen would also cause conflict.

Thanks,
Sam

**Comment by edubxb** [comment]
100% agree.

**Comment by tswicegood** [comment]
I'm open to renaming it -- would like to have a way to keep it around for people who use it.  Maybe detect if `pass` is already on the path, and not set the alias unless `BASH_IT_LEGACY_PASS` is true or some such?  @scmorrison care to take a stab at an implementation?

**Comment by scmorrison** [comment]
Ok, well here is a [first stab](https://github.com/scmorrison/bash-it/blob/master/plugins/available/base.plugin.bash#L42-L61). 

This is the flow:

1. Define function passgen (instead of pass)
2. If the pass command (password store) is not installed or BASH_IT_LEGACY_PASS is true then define alias pass.

````bash
function passgen ()
{
    about 'generates random password from dictionary words'
    param 'optional integer length'
    param 'if unset, defaults to 4'
    example '$ passgen'
    example '$ passgen 6'
    group 'base'
    local i passgen length=${1:-4}
    pass=$(echo $(for i in $(eval echo "{1..$length}"); do pickfrom /usr/share/dict/words; done))
    echo "With spaces (easier to memorize): $pass"
    echo "Without (use this as the password): $(echo $pass | tr -d ' ')"
}

# Create alias pass to passgen when pass isn't installed or
# BASH_IT_LEGACY_PASS is true.
if ! command -v pass &>/dev/null || [ "$BASH_IT_LEGACY_PASS" == 1 ]
then
  alias pass=passgen
fi
````
Also, I wasn't able to find any existing Linux command called passgen so I think this name is safe. If all looks good then I will do a pull request.

Thanks,
Sam

**Comment by nwinkler** [comment]
Looks good to me!

**Comment by edubxb** [comment]
Looks good! :+1:

**Comment by edubxb** [comment]
If you can, update the README to comment the new BASH_IT_LEGACY_PASS variable.
